### PR TITLE
skip migrations upon request

### PR DESCRIPTION
**Pull request by javierg**
Adding property skip_migrations to db setup so we can skip them when the same db is used in different regions

### CODE REVIEW

**Review by brlanier — COMMENTED** [review]
Looks simple enough.
tests?

**Comment by javierg** [comment]
working on tests

**Review by brlanier — APPROVED** [review]
I suppose this works better when asking for test to actually have tests running in a CI

This seems to work as advertised
have someone else review the code, but it worked for my purposes

:shipit:

**Review by louismanson — APPROVED** [review]
:shipit:

**Pull request merged**
