### PR TITLE
Feature/type mango query

### PR DESCRIPTION
**Pull request by ErickFabian**
Enables querys such as: 
`query = {and: [{ type: { eq: 'user' } } , { username: { eq: 'ErickFabian'}} ]}`
`User.where(query)`
=> `[....]`

and

`User.where({username: { "$type": "null"}})`

### CODE REVIEW

**Comment by javierg** [comment]
what will `User.where({username: { "$type": "null"}})` return?

**Comment by ErickFabian** [comment]
@javierg 

```
[#<User:0x00007fcedd9d4960
  @account_active=true,
  @allocated_aluzo=false,
  @type=nil,
  @username=nil>,
 #<User:0x00007fcee43a4110
  @account_active=true,
  @allocated_aluzo=false,
  @username=nil
]
```

returns an array of objects that have nil usernames

**Comment by ErickFabian** [comment]
@javierg Should i validate the correct values are used for the `$type` operator as a better developer experience? 

`Valid values are "null", "boolean", "number", "string", "array", and "object".`

**Review by javierg — APPROVED** [review]
:shipit:

**Pull request merged**
