### PR TITLE
add hash with indifferent access fixes #35

### LINKED ISSUE #35: Nested Attributes Should Be Accessible by String or Symbol
If you have a nested attribute:

```
'sender': {
  type: 'mysql',
  id: 1
}
```

`doc['sender']` works, but `doc['sender']['id']` doesn't work, you have to do `doc['sender'][:id]`. There's some weird inconsistencies, sometimes you need strings, sometimes symbols.

### PR DESCRIPTION
**Pull request by seancookr**
Needs a test

Needs Review as well

### CODE REVIEW

**Comment by rubenrails** [comment]
:shipit:

**Comment by rubenrails** [comment]
Test looks good also. :shipit:

**Comment by seancookr** [comment]
@javierg @neojin @rubenrails I'd like to discuss the merits of this before we merge it.  This would be really nice, but again would include an active-support dependency.  I could make a `Dolly::HashWIthInDifferentAccess`, but I am partial to using something that has already been written and tested a bunch.  I would love to hear other opinions.

**Comment by javierg** [comment]
> but I am partial to using something that has already been written 

So lets just use `CouchRestModel` then :trollface:

**Comment by neojin** [comment]
This is probably a dumb question but why not convert string based hash keys to symbols and do away with HashWithIndifferentAccess?

**Comment by javierg** [comment]
> This is probably a dumb question but why not convert string based hash keys to symbols and do away with HashWithIndifferentAccess?

:+1:

**Comment by seancookr** [comment]
this is stale and old, closing

**Pull request closed without merging**
